// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh7VcrqdfUKgBckE8Xl-Mzy1PncCw-thU',
    appId: '1:336840296765:web:5d2f4106ce550dbb3c1d54',
    messagingSenderId: '336840296765',
    projectId: 'fir-crud-d644f',
    authDomain: 'fir-crud-d644f.firebaseapp.com',
    storageBucket: 'fir-crud-d644f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBfC7ean0FmlaooG37qzZ-caRHv5oS9PM',
    appId: '1:336840296765:android:feec2f2efab94f0e3c1d54',
    messagingSenderId: '336840296765',
    projectId: 'fir-crud-d644f',
    storageBucket: 'fir-crud-d644f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTvb5ln1qGK3vu4VlkHw-uPakjCsB7hZw',
    appId: '1:336840296765:ios:343372802f2c1b863c1d54',
    messagingSenderId: '336840296765',
    projectId: 'fir-crud-d644f',
    storageBucket: 'fir-crud-d644f.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTvb5ln1qGK3vu4VlkHw-uPakjCsB7hZw',
    appId: '1:336840296765:ios:343372802f2c1b863c1d54',
    messagingSenderId: '336840296765',
    projectId: 'fir-crud-d644f',
    storageBucket: 'fir-crud-d644f.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh7VcrqdfUKgBckE8Xl-Mzy1PncCw-thU',
    appId: '1:336840296765:web:6e064463f681068e3c1d54',
    messagingSenderId: '336840296765',
    projectId: 'fir-crud-d644f',
    authDomain: 'fir-crud-d644f.firebaseapp.com',
    storageBucket: 'fir-crud-d644f.appspot.com',
  );
}
